config:
  default: true
  MD013: false
  MD024: false
  MD033: false
ignores:
  - "**/node_modules/**"
  - "**/dist/**"
  - "**/build/**"
  - "**/out/**"
  - "**/cache/**"
  - "wallets/**"
  - "**/lib/**"
