export const AGENT_NFT_ABI = [
  "function ADMIN_ROLE() view returns (bytes32)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function MAX_AUTHORIZED_USERS() view returns (uint256)",
  "function MINTER_ROLE() view returns (bytes32)",
  "function UPGRADE_INTERFACE_VERSION() view returns (string)",
  "function approve(address to, uint256 tokenId)",
  "function authorizeUsage(uint256 tokenId, address to)",
  "function authorizedUsersOf(uint256 tokenId) view returns (address[])",
  "function balanceOf(address owner) view returns (uint256)",
  "function cancelFeeWithdrawal()",
  "function cancelUpgrade()",
  "function cancelVerifierProposal()",
  "function creatorOf(uint256 tokenId) view returns (address)",
  "function delegateAccess(address assistant)",
  "function executeFeeWithdrawal()",
  "function executeUpgrade()",
  "function executeVerifier()",
  "function getApproved(uint256 tokenId) view returns (address)",
  "function getDelegateAccess(address user) view returns (address)",
  "function getRoleAdmin(bytes32 role) view returns (bytes32)",
  "function grantRole(bytes32 role, address account)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function iClone(address to, uint256 tokenId, ((bytes32 dataHash, bytes targetPubkey, bytes nonce, bytes proof, uint256 validUntil) accessProof, (uint8 oracleType, bytes32 dataHash, bytes sealedKey, bytes targetPubkey, bytes nonce, bytes proof, uint256 validUntil) ownershipProof)[] proofs) returns (uint256 newTokenId)",
  "function iCloneFrom(address from, address to, uint256 tokenId, ((bytes32 dataHash, bytes targetPubkey, bytes nonce, bytes proof, uint256 validUntil) accessProof, (uint8 oracleType, bytes32 dataHash, bytes sealedKey, bytes targetPubkey, bytes nonce, bytes proof, uint256 validUntil) ownershipProof)[] proofs) returns (uint256)",
  "function iTransfer(address to, uint256 tokenId, ((bytes32 dataHash, bytes targetPubkey, bytes nonce, bytes proof, uint256 validUntil) accessProof, (uint8 oracleType, bytes32 dataHash, bytes sealedKey, bytes targetPubkey, bytes nonce, bytes proof, uint256 validUntil) ownershipProof)[] proofs)",
  "function iTransferFrom(address from, address to, uint256 tokenId, ((bytes32 dataHash, bytes targetPubkey, bytes nonce, bytes proof, uint256 validUntil) accessProof, (uint8 oracleType, bytes32 dataHash, bytes sealedKey, bytes targetPubkey, bytes nonce, bytes proof, uint256 validUntil) ownershipProof)[] proofs)",
  "function initialize(string name_, string symbol_, string storageInfo_, address verifierAddr, address admin_)",
  "function intelligentDataOf(uint256 tokenId) view returns ((string dataDescription, bytes32 dataHash)[] data)",
  "function intelligentDatasOf(uint256 tokenId) view returns ((string dataDescription, bytes32 dataHash)[])",
  "function isApprovedForAll(address owner, address operator) view returns (bool)",
  "function mint((string dataDescription, bytes32 dataHash)[] iDatas, address to) payable returns (uint256 tokenId)",
  "function mintFee() view returns (uint256)",
  "function mintWithRole((string dataDescription, bytes32 dataHash)[] iDatas, address to) returns (uint256 tokenId)",
  "function mintWithRole((string dataDescription, bytes32 dataHash)[] iDatas, address to, address creator) returns (uint256 tokenId)",
  "function name() view returns (string)",
  "function ownerOf(uint256 tokenId) view returns (address)",
  "function pause()",
  "function paused() view returns (bool)",
  "function pendingFeeWithdrawal() view returns (address)",
  "function pendingFeeWithdrawalExecutableAt() view returns (uint256)",
  "function pendingUpgrade() view returns (address)",
  "function pendingUpgradeExecutableAt() view returns (uint256)",
  "function pendingVerifier() view returns (address)",
  "function pendingVerifierExecutableAt() view returns (uint256)",
  "function proposeFeeWithdrawal(address to)",
  "function proposeUpgrade(address newImplementation)",
  "function proposeVerifier(address newVerifier)",
  "function proxiableUUID() view returns (bytes32)",
  "function renounceRole(bytes32 role, address callerConfirmation)",
  "function revokeAuthorization(uint256 tokenId, address user)",
  "function revokeRole(bytes32 role, address account)",
  "function safeTransferFrom(address from, address to, uint256 tokenId)",
  "function safeTransferFrom(address from, address to, uint256 tokenId, bytes data)",
  "function setApprovalForAll(address operator, bool approved)",
  "function setMintFee(uint256 newFee)",
  "function setStorageInfo(string newInfo)",
  "function storageInfo() view returns (string)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function symbol() view returns (string)",
  "function tokenURI(uint256 tokenId) view returns (string)",
  "function transferAndCleanExpiredProofs(address from, address to, uint256 tokenId, ((bytes32 dataHash, bytes targetPubkey, bytes nonce, bytes proof, uint256 validUntil) accessProof, (uint8 oracleType, bytes32 dataHash, bytes sealedKey, bytes targetPubkey, bytes nonce, bytes proof, uint256 validUntil) ownershipProof)[] proofs, bytes32[] cleanupNonces)",
  "function transferFrom(address from, address to, uint256 tokenId)",
  "function unpause()",
  "function update(uint256 tokenId, (string dataDescription, bytes32 dataHash)[] newDatas)",
  "function upgradeToAndCall(address newImplementation, bytes data) payable",
  "function verifier() view returns (address)",
  "function withdrawMintFees(address) view",
  "event Approval(address indexed owner, address indexed approved, uint256 indexed tokenId)",
  "event ApprovalForAll(address indexed owner, address indexed operator, bool approved)",
  "event Authorization(address indexed from, address indexed to, uint256 indexed tokenId)",
  "event AuthorizationRevoked(address indexed from, address indexed to, uint256 indexed tokenId)",
  "event Cloned(uint256 indexed tokenId, uint256 indexed newTokenId, address from, address to)",
  "event CreatorSet(uint256 indexed tokenId, address indexed creator)",
  "event DelegateAccess(address indexed user, address indexed assistant)",
  "event FeeWithdrawalCancelled()",
  "event FeeWithdrawalExecuted(address indexed to, uint256 amount)",
  "event FeeWithdrawalProposed(address indexed to)",
  "event Initialized(uint64 version)",
  "event MetadataJsonDecisionDocumented(string collectionName, string collectionSymbol, string rationaleTag)",
  "event MintFeeUpdated(uint256 oldFee, uint256 newFee)",
  "event Paused(address account)",
  "event PublishedSealedKey(address indexed to, uint256 indexed tokenId, bytes[] sealedKeys)",
  "event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)",
  "event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)",
  "event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)",
  "event StorageInfoUpdated(string oldInfo, string newInfo)",
  "event Transfer(address indexed from, address indexed to, uint256 indexed tokenId)",
  "event Transferred(uint256 indexed _tokenId, address indexed _from, address indexed _to)",
  "event Unpaused(address account)",
  "event Updated(uint256 indexed tokenId, (string dataDescription, bytes32 dataHash)[] oldDatas, (string dataDescription, bytes32 dataHash)[] newDatas)",
  "event UpgradeCancelled()",
  "event UpgradeExecuted(address indexed newImplementation)",
  "event UpgradeProposed(address indexed newImplementation)",
  "event Upgraded(address indexed implementation)",
  "event VerifierProposalCancelled()",
  "event VerifierProposed(address indexed newVerifier)",
  "event VerifierUpdated(address indexed oldVerifier, address indexed newVerifier)",
  "error AccessControlBadConfirmation()",
  "error AccessControlUnauthorizedAccount(address account, bytes32 neededRole)",
  "error AddressEmptyCode(address target)",
  "error DelayNotElapsed(uint256 remaining)",
  "error ERC1967InvalidImplementation(address implementation)",
  "error ERC1967NonPayable()",
  "error ERC721IncorrectOwner(address sender, uint256 tokenId, address owner)",
  "error ERC721InsufficientApproval(address operator, uint256 tokenId)",
  "error ERC721InvalidApprover(address approver)",
  "error ERC721InvalidOperator(address operator)",
  "error ERC721InvalidOwner(address owner)",
  "error ERC721InvalidReceiver(address receiver)",
  "error ERC721InvalidSender(address sender)",
  "error ERC721NonexistentToken(uint256 tokenId)",
  "error ERC7857AccessAssistantMismatch()",
  "error ERC7857AlreadyAuthorized()",
  "error ERC7857DataHashMismatch()",
  "error ERC7857EmptyProof()",
  "error ERC7857InvalidAssistant(address _assistant)",
  "error ERC7857InvalidAuthorizedUser(address user)",
  "error ERC7857NotAuthorized()",
  "error ERC7857ProofCountMismatch()",
  "error ERC7857TargetPubkeyMismatch()",
  "error ERC7857TooManyAuthorizedUsers()",
  "error ERC7857WantedReceiverMismatch()",
  "error EnforcedPause()",
  "error ExpectedPause()",
  "error FailedInnerCall()",
  "error InvalidInitialization()",
  "error NoPendingProposal()",
  "error NotInitializing()",
  "error ReentrancyGuardReentrantCall()",
  "error UUPSUnauthorizedCallContext()",
  "error UUPSUnsupportedProxiableUUID(bytes32 slot)",
  "error UnauthorizedUsage(address caller)",
  "error UseITransferWithProofs()",
  "error UseTimelockedFeeWithdrawal()"
] as const;

// Human-readable iTransferFrom fragment for viem-based wallet callers (frontend useTransfer);
// mirrors the tuple() encoding in the main AGENT_NFT_ABI transferAndCleanExpiredProofs entry.
export const ITRANSFER_FROM_ABI = [
  {
    type: "function",
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
      {
        name: "proofs",
        internalType: "struct TransferValidityProof[]",
        type: "tuple[]",
        components: [
          {
            name: "accessProof",
            internalType: "struct AccessProof",
            type: "tuple",
            components: [
              { name: "dataHash", internalType: "bytes32", type: "bytes32" },
              { name: "targetPubkey", internalType: "bytes", type: "bytes" },
              { name: "nonce", internalType: "bytes", type: "bytes" },
              { name: "proof", internalType: "bytes", type: "bytes" },
              { name: "validUntil", internalType: "uint256", type: "uint256" },
            ],
          },
          {
            name: "ownershipProof",
            internalType: "struct OwnershipProof",
            type: "tuple",
            components: [
              { name: "oracleType", internalType: "enum OracleType", type: "uint8" },
              { name: "dataHash", internalType: "bytes32", type: "bytes32" },
              { name: "sealedKey", internalType: "bytes", type: "bytes" },
              { name: "targetPubkey", internalType: "bytes", type: "bytes" },
              { name: "nonce", internalType: "bytes", type: "bytes" },
              { name: "proof", internalType: "bytes", type: "bytes" },
              { name: "validUntil", internalType: "uint256", type: "uint256" },
            ],
          },
        ],
      },
    ],
    name: "iTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;
