export const DELEGATION_REGISTRY_ABI = [
  "function delegatedExecute(uint256,address,uint256,bytes,bytes32[]) payable returns (bytes)",
  "function domainSeparator() view returns (bytes32)",
  "function getDelegation(uint256) view returns ((uint256,address,uint256,uint256,uint64,uint64,bytes32,uint256))",
  "function installDelegation((uint256,address,uint256,uint256,uint64,uint64,bytes32,uint256),bytes)",
  "function isDelegationActive(uint256) view returns (bool)",
  "function nft() view returns (address)",
  "function owner() view returns (address)",
  "function pause()",
  "function paused() view returns (bool)",
  "function renounceOwnership()",
  "function revokeDelegation(uint256)",
  "function transferOwnership(address)",
  "function unpause()",
  "function usedNonces(uint256,uint256) view returns (bool)",
  "function windows(uint256) view returns (uint128,uint64)",
  "event DelegatedExecuted(uint256 indexed,address indexed,address indexed,uint256,bytes32)",
  "event DelegationInstalled(uint256 indexed,address indexed,uint64,uint256,uint256)",
  "event DelegationRevoked(uint256 indexed)",
  "event OwnershipTransferred(address indexed,address indexed)",
  "event Paused(address)",
  "event Unpaused(address)",
  "error CallFailed()",
  "error CapExceeded()",
  "error DelegationExpired()",
  "error DelegationNonceUsed()",
  "error ECDSAInvalidSignature()",
  "error ECDSAInvalidSignatureLength(uint256)",
  "error ECDSAInvalidSignatureS(bytes32)",
  "error EnforcedPause()",
  "error ExpectedPause()",
  "error InvalidMerkleProof()",
  "error InvalidWindowConfig()",
  "error NoActiveDelegation()",
  "error NotDelegate()",
  "error NotTokenOwner()",
  "error OwnableInvalidOwner(address)",
  "error OwnableUnauthorizedAccount(address)",
  "error ReentrancyGuardReentrantCall()",
  "error SelectorNotAllowed()",
  "error ValueMismatch(uint256,uint256)",
  "error WindowExceeded()",
  "error ZeroAddress()",
] as const;
