export const DELEGATION_REGISTRY_ABI = [
  "function delegatedExecute(uint256 agentTokenId, address target, uint256 value, bytes data, bytes32[] merkleProof) payable returns (bytes)",
  "function domainSeparator() view returns (bytes32)",
  "function getDelegation(uint256 agentTokenId) view returns ((uint256 agentTokenId, address delegate, uint256 perTxCap, uint256 windowCap, uint64 windowSeconds, uint64 expiresAt, bytes32 allowedSelectorsRoot, uint256 nonce))",
  "function installDelegation((uint256 agentTokenId, address delegate, uint256 perTxCap, uint256 windowCap, uint64 windowSeconds, uint64 expiresAt, bytes32 allowedSelectorsRoot, uint256 nonce) d, bytes ownerSig)",
  "function isDelegationActive(uint256 agentTokenId) view returns (bool)",
  "function nft() view returns (address)",
  "function owner() view returns (address)",
  "function pause()",
  "function paused() view returns (bool)",
  "function renounceOwnership()",
  "function revokeDelegation(uint256 agentTokenId)",
  "function transferOwnership(address newOwner)",
  "function unpause()",
  "function usedNonces(uint256 agentTokenId, uint256 nonce) view returns (bool used)",
  "function windows(uint256 agentTokenId) view returns (uint128 spent, uint64 windowId)",
  "event DelegatedExecuted(uint256 indexed agentTokenId, address indexed delegate, address indexed target, uint256 value, bytes32 actionHash)",
  "event DelegationInstalled(uint256 indexed agentTokenId, address indexed delegate, uint64 expiresAt, uint256 perTxCap, uint256 windowCap)",
  "event DelegationRevoked(uint256 indexed agentTokenId)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event Paused(address account)",
  "event Unpaused(address account)",
  "error CallFailed()",
  "error CapExceeded()",
  "error DelegationExpired()",
  "error DelegationNonceUsed()",
  "error ECDSAInvalidSignature()",
  "error ECDSAInvalidSignatureLength(uint256 length)",
  "error ECDSAInvalidSignatureS(bytes32 s)",
  "error EnforcedPause()",
  "error ExpectedPause()",
  "error InvalidMerkleProof()",
  "error InvalidWindowConfig()",
  "error NoActiveDelegation()",
  "error NotDelegate()",
  "error NotTokenOwner()",
  "error OwnableInvalidOwner(address owner)",
  "error OwnableUnauthorizedAccount(address account)",
  "error ReentrancyGuardReentrantCall()",
  "error SelectorNotAllowed()",
  "error ValueMismatch(uint256 value, uint256 msgValue)",
  "error WindowExceeded()",
  "error ZeroAddress()"
] as const;
