export const PAYMENT_PROCESSOR_ABI = [
  "function AXIOM_NFT() view returns (address)",
  "function BPS_DENOMINATOR() view returns (uint256)",
  "function UPGRADE_INTERFACE_VERSION() view returns (string)",
  "function agentEarningsOf(address creator) view returns (uint256)",
  "function cancelProtocolTreasuryProposal()",
  "function executeProtocolTreasury()",
  "function initialize(address nftAddr, address paymentTokenAddr, address treasuryAddr, uint256 protocolFeeBps_, address initialOwner)",
  "function owner() view returns (address)",
  "function pause()",
  "function paused() view returns (bool)",
  "function payComputeProvider(address provider, uint256 amount)",
  "function payForAgent(uint256 agentTokenId, uint256 amount)",
  "function paymentToken() view returns (address)",
  "function pendingProtocolTreasury() view returns (address)",
  "function pendingTreasuryEffectiveAt() view returns (uint256)",
  "function proposeProtocolTreasury(address newTreasury)",
  "function protocolFeeBps() view returns (uint256)",
  "function protocolTreasury() view returns (address)",
  "function proxiableUUID() view returns (bytes32)",
  "function renounceOwnership()",
  "function royaltyBpsOf(uint256 agentTokenId) view returns (uint256)",
  "function royaltyBpsSet(uint256 agentTokenId) view returns (bool)",
  "function setPaymentToken(address newPaymentToken)",
  "function setProtocolFeeBps(uint256 newBps)",
  "function setRoyaltyBps(uint256 agentTokenId, uint256 newBps)",
  "function setRoyaltyBpsPermitted(uint256 agentTokenId, uint256 newBps)",
  "function totalOutstandingEarnings() view returns (uint256)",
  "function transferOwnership(address newOwner)",
  "function unpause()",
  "function upgradeToAndCall(address newImplementation, bytes data) payable",
  "function withdrawAgentEarnings()",
  "event ComputeProviderPaid(address indexed provider, uint256 amount)",
  "event EarningsWithdrawn(address indexed creator, uint256 amount)",
  "event Initialized(uint64 version)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event Paused(address account)",
  "event PaymentProcessed(uint256 indexed agentTokenId, address indexed payer, address indexed creator, uint256 amount, uint256 creatorCut, uint256 protocolCut)",
  "event PaymentTokenUpdated(address indexed oldToken, address indexed newToken)",
  "event ProtocolFeeBpsUpdated(uint256 oldBps, uint256 newBps)",
  "event ProtocolTreasuryProposalCancelled(address indexed pendingTreasury)",
  "event ProtocolTreasuryProposed(address indexed proposedTreasury, uint256 effectiveAt)",
  "event ProtocolTreasuryUpdated(address indexed oldTreasury, address indexed newTreasury)",
  "event RoyaltySet(uint256 indexed agentTokenId, uint256 bps)",
  "event Unpaused(address account)",
  "event Upgraded(address indexed implementation)",
  "error AddressEmptyCode(address target)",
  "error AddressInsufficientBalance(address account)",
  "error AgentCreatorNotRegistered()",
  "error DelayNotElapsed(uint256 remaining)",
  "error ERC1967InvalidImplementation(address implementation)",
  "error ERC1967NonPayable()",
  "error EnforcedPause()",
  "error ExpectedPause()",
  "error FailedInnerCall()",
  "error InvalidBps()",
  "error InvalidInitialization()",
  "error MigrationBlocked()",
  "error NoEarnings()",
  "error NoPendingProposal()",
  "error NoPendingProposal()",
  "error NotCreator()",
  "error NotInitializing()",
  "error OwnableInvalidOwner(address owner)",
  "error OwnableUnauthorizedAccount(address account)",
  "error ReentrancyGuardReentrantCall()",
  "error SafeERC20FailedOperation(address token)",
  "error TransferAmountMismatch(uint256 expected, uint256 received)",
  "error UUPSUnauthorizedCallContext()",
  "error UUPSUnsupportedProxiableUUID(bytes32 slot)",
  "error ZeroAddress()",
  "error ZeroAmount()"
] as const;
