export const PAYMENT_PROCESSOR_ABI = [
  "function ADMIN_ROLE() view returns (bytes32)",
  "function AXIOM_NFT() view returns (address)",
  "function BPS_DENOMINATOR() view returns (uint256)",
  "function DEFAULT_ADMIN_ROLE() view returns (bytes32)",
  "function PERMIT2() view returns (address)",
  "function UPGRADE_INTERFACE_VERSION() view returns (string)",
  "function agentEarningsOf(address creator) view returns (uint256)",
  "function axiomVault() view returns (address)",
  "function cancelProtocolTreasuryProposal()",
  "function computeRatioMax() view returns (uint256)",
  "function effectiveRoyaltyBpsOf(uint256 tokenId) view returns (uint256 royaltyBps, bool isSet, uint256 protocolFeeBps)",
  "function executeProtocolTreasury()",
  "function getRoleAdmin(bytes32 role) view returns (bytes32)",
  "function grantRole(bytes32 role, address account)",
  "function hasRole(bytes32 role, address account) view returns (bool)",
  "function initialize(address nftAddr, address paymentTokenAddr, address treasuryAddr, uint256 protocolFeeBps_, address initialOwner)",
  "function maxPayCap() view returns (uint256)",
  "function pause()",
  "function paused() view returns (bool)",
  "function payComputeProvider(address provider, uint256 amount)",
  "function payForAgent(uint256 agentTokenId, uint256 amount)",
  "function payForAgentAndCompute(uint256 agentTokenId, address provider, uint256 agentAmount, uint256 computeAmount)",
  "function payForAgentWithPermit2(uint256 agentTokenId, uint256 amount, address owner, ((address token, uint256 amount) permitted, uint256 nonce, uint256 deadline) permit, bytes signature)",
  "function paymentSnapshot(address payer, uint256 tokenId) view returns (uint256 maxPayCap, uint256 computeRatioMax, uint256 agentBalance, uint256 payerAllowance, address paymentToken)",
  "function paymentToken() view returns (address)",
  "function pendingProtocolTreasury() view returns (address)",
  "function pendingTreasuryEffectiveAt() view returns (uint256)",
  "function proposeProtocolTreasury(address newTreasury)",
  "function protocolFeeBps() view returns (uint256)",
  "function protocolTreasury() view returns (address)",
  "function proxiableUUID() view returns (bytes32)",
  "function renounceRole(bytes32 role, address callerConfirmation)",
  "function revokeRole(bytes32 role, address account)",
  "function royaltyBpsOf(uint256 agentTokenId) view returns (uint256)",
  "function royaltyBpsSet(uint256 agentTokenId) view returns (bool)",
  "function royaltyRecipientOf(uint256 tokenId) view returns (address recipient)",
  "function setAxiomVault(address newVault)",
  "function setComputeRatioMax(uint256 newRatioMax)",
  "function setMaxPayCap(uint256 newCap)",
  "function setPaymentToken(address newPaymentToken)",
  "function setProtocolFeeBps(uint256 newBps)",
  "function setRoyaltyBps(uint256 agentTokenId, uint256 newBps)",
  "function supportsInterface(bytes4 interfaceId) view returns (bool)",
  "function totalOutstandingEarnings() view returns (uint256)",
  "function unpause()",
  "function upgradeToAndCall(address newImplementation, bytes data) payable",
  "function vaultHealthOf(uint256 tokenId) view returns (uint256 balance, bytes32 strategyRoot, uint128 dailyLimit, uint128 dailySpent, uint64 resetDay, uint64 validUntilDay, bool expired)",
  "function verifyPayloadOf(uint256 tokenId, uint256 dataIndex, bytes payload) view returns (bool)",
  "function withdrawAgentEarnings()",
  "event ComputeProviderPaid(address indexed provider, uint256 amount)",
  "event ComputeRatioMaxUpdated(uint256 oldRatioMax, uint256 newRatioMax)",
  "event EarningsWithdrawn(address indexed creator, uint256 amount)",
  "event Initialized(uint64 version)",
  "event MaxPayCapUpdated(uint256 oldCap, uint256 newCap)",
  "event Paused(address account)",
  "event PaymentProcessed(uint256 indexed agentTokenId, address indexed payer, address indexed creator, uint256 amount, uint256 creatorCut, uint256 protocolCut)",
  "event PaymentTokenUpdated(address indexed oldToken, address indexed newToken)",
  "event ProtocolFeeBpsUpdated(uint256 oldBps, uint256 newBps)",
  "event ProtocolTreasuryProposalCancelled(address indexed pendingTreasury)",
  "event ProtocolTreasuryProposed(address indexed proposedTreasury, uint256 effectiveAt)",
  "event ProtocolTreasuryUpdated(address indexed oldTreasury, address indexed newTreasury)",
  "event RoleAdminChanged(bytes32 indexed role, bytes32 indexed previousAdminRole, bytes32 indexed newAdminRole)",
  "event RoleGranted(bytes32 indexed role, address indexed account, address indexed sender)",
  "event RoleRevoked(bytes32 indexed role, address indexed account, address indexed sender)",
  "event RoyaltySet(uint256 indexed agentTokenId, uint256 bps)",
  "event Unpaused(address account)",
  "event Upgraded(address indexed implementation)",
  "event VaultAddressUpdated(address indexed oldVault, address indexed newVault)",
  "error AccessControlBadConfirmation()",
  "error AccessControlUnauthorizedAccount(address account, bytes32 neededRole)",
  "error AddressEmptyCode(address target)",
  "error AddressInsufficientBalance(address account)",
  "error AgentCreatorNotRegistered()",
  "error ComputeRatioExceeded(uint256 computeAmount, uint256 maxCompute)",
  "error DelayNotElapsed(uint256 remaining)",
  "error ERC1967InvalidImplementation(address implementation)",
  "error ERC1967NonPayable()",
  "error EnforcedPause()",
  "error ExpectedPause()",
  "error FailedInnerCall()",
  "error InvalidBps()",
  "error InvalidInitialization()",
  "error InvalidPermitAmount(uint256 permitted, uint256 requested)",
  "error InvalidPermitToken()",
  "error MigrationBlocked()",
  "error NoEarnings()",
  "error NoPendingProposal()",
  "error NoPendingProposal()",
  "error NotCreator()",
  "error NotInitializing()",
  "error PayAmountExceedsCap(uint256 amount, uint256 cap)",
  "error PermitExpired(uint256 deadline, uint256 timestamp)",
  "error ReentrancyGuardReentrantCall()",
  "error SafeERC20FailedOperation(address token)",
  "error TransferAmountMismatch(uint256 expected, uint256 received)",
  "error UUPSUnauthorizedCallContext()",
  "error UUPSUnsupportedProxiableUUID(bytes32 slot)",
  "error VaultNotConfigured()",
  "error ZeroAddress()",
  "error ZeroAmount()"
] as const;
