export const TEE_VERIFIER_ABI = [
  "function UPGRADE_INTERFACE_VERSION() view returns (string)",
  "function cancelSignerProposal()",
  "function cleanExpiredProofs(bytes32[] proofNonces)",
  "function domainSeparator() view returns (bytes32)",
  "function executeSigner()",
  "function initialize(address _owner, address _signer, uint256 _maxProofAge)",
  "function maxProofAgeSeconds() view returns (uint256)",
  "function owner() view returns (address)",
  "function pendingSigner() view returns (address)",
  "function proposeSigner(address newSigner)",
  "function proxiableUUID() view returns (bytes32)",
  "function registeredSigner() view returns (address)",
  "function renounceOwnership()",
  "function transferOwnership(address newOwner)",
  "function upgradeToAndCall(address newImplementation, bytes data) payable",
  "function verifyTransferValidity(((bytes32 dataHash, bytes targetPubkey, bytes nonce, bytes proof, uint256 validUntil) accessProof, (uint8 oracleType, bytes32 dataHash, bytes sealedKey, bytes targetPubkey, bytes nonce, bytes proof, uint256 validUntil) ownershipProof)[] proofs, address to, address nft) returns ((bytes32 dataHash, bytes sealedKey, bytes targetPubkey, bytes wantedKey, address accessAssistant, bytes accessProofNonce, bytes ownershipProofNonce)[] outputs)",
  "event Initialized(uint64 version)",
  "event OwnershipTransferred(address indexed previousOwner, address indexed newOwner)",
  "event SignerExecuted(address indexed oldSigner, address indexed newSigner)",
  "event SignerProposalCancelled(address indexed cancelledSigner)",
  "event SignerProposed(address indexed newSigner, uint256 executableAt)",
  "event Upgraded(address indexed implementation)",
  "error AddressEmptyCode(address target)",
  "error AxiomInvalidAccessProof()",
  "error AxiomInvalidOwnershipProof()",
  "error AxiomInvalidSigner()",
  "error AxiomProofExpired(uint256 validUntil, uint256 blockTimestamp)",
  "error AxiomValidUntilTooFar(uint256 validUntil, uint256 blockTimestamp, uint256 maxProofAgeSeconds)",
  "error DelayNotElapsed(uint256 remaining)",
  "error ECDSAInvalidSignature()",
  "error ECDSAInvalidSignatureLength(uint256 length)",
  "error ECDSAInvalidSignatureS(bytes32 s)",
  "error ERC1967InvalidImplementation(address implementation)",
  "error ERC1967NonPayable()",
  "error FailedInnerCall()",
  "error InvalidInitialization()",
  "error NoPendingProposal()",
  "error NotInitializing()",
  "error OwnableInvalidOwner(address owner)",
  "error OwnableUnauthorizedAccount(address account)",
  "error ProofAlreadyUsed(bytes32 proofHash)",
  "error ProofFieldMismatch()",
  "error UUPSUnauthorizedCallContext()",
  "error UUPSUnsupportedProxiableUUID(bytes32 slot)",
  "error ZeroAddress()",
] as const;
